// Mocks generated by Mockito 5.4.6 from annotations
// in music_app/test/services/youtube_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:convert' as _i8;
import 'dart:typed_data' as _i9;

import 'package:http/http.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:music_app/models/music_models.dart' as _i4;
import 'package:music_app/services/gemini_service.dart' as _i11;
import 'package:music_app/services/music_server_service.dart' as _i10;
import 'package:music_app/services/youtube_service.dart' as _i5;
import 'package:youtube_explode_dart/youtube_explode_dart.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVideo_0 extends _i1.SmartFake implements _i2.Video {
  _FakeVideo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_1 extends _i1.SmartFake implements _i3.Response {
  _FakeResponse_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamedResponse_2 extends _i1.SmartFake
    implements _i3.StreamedResponse {
  _FakeStreamedResponse_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMusicSearchResult_3 extends _i1.SmartFake
    implements _i4.MusicSearchResult {
  _FakeMusicSearchResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [YoutubeGateway].
///
/// See the documentation for Mockito's code generation for more information.
class MockYoutubeGateway extends _i1.Mock implements _i5.YoutubeGateway {
  MockYoutubeGateway() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i2.Video>> search(
    String? query, {
    int? limit = 5,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #search,
          [query],
          {#limit: limit},
        ),
        returnValue: _i6.Future<List<_i2.Video>>.value(<_i2.Video>[]),
      ) as _i6.Future<List<_i2.Video>>);

  @override
  _i6.Future<String> getAudioUrl(String? videoId) => (super.noSuchMethod(
        Invocation.method(
          #getAudioUrl,
          [videoId],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getAudioUrl,
            [videoId],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i2.Video> getVideo(String? videoId) => (super.noSuchMethod(
        Invocation.method(
          #getVideo,
          [videoId],
        ),
        returnValue: _i6.Future<_i2.Video>.value(_FakeVideo_0(
          this,
          Invocation.method(
            #getVideo,
            [videoId],
          ),
        )),
      ) as _i6.Future<_i2.Video>);

  @override
  _i6.Future<
      ({String playlistTitle, List<_i2.Video> videos})> getPlaylistVideos(
          String? playlistId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPlaylistVideos,
          [playlistId],
        ),
        returnValue:
            _i6.Future<({String playlistTitle, List<_i2.Video> videos})>.value((
          playlistTitle: _i7.dummyValue<String>(
            this,
            Invocation.method(
              #getPlaylistVideos,
              [playlistId],
            ),
          ),
          videos: <_i2.Video>[]
        )),
      ) as _i6.Future<({String playlistTitle, List<_i2.Video> videos})>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockClient extends _i1.Mock implements _i3.Client {
  MockClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Response> head(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #head,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> get(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #get,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> post(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #post,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> put(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #put,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> patch(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #patch,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<_i3.Response> delete(
    Uri? url, {
    Map<String, String>? headers,
    Object? body,
    _i8.Encoding? encoding,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [url],
          {
            #headers: headers,
            #body: body,
            #encoding: encoding,
          },
        ),
        returnValue: _i6.Future<_i3.Response>.value(_FakeResponse_1(
          this,
          Invocation.method(
            #delete,
            [url],
            {
              #headers: headers,
              #body: body,
              #encoding: encoding,
            },
          ),
        )),
      ) as _i6.Future<_i3.Response>);

  @override
  _i6.Future<String> read(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #read,
            [url],
            {#headers: headers},
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<_i9.Uint8List> readBytes(
    Uri? url, {
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readBytes,
          [url],
          {#headers: headers},
        ),
        returnValue: _i6.Future<_i9.Uint8List>.value(_i9.Uint8List(0)),
      ) as _i6.Future<_i9.Uint8List>);

  @override
  _i6.Future<_i3.StreamedResponse> send(_i3.BaseRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #send,
          [request],
        ),
        returnValue:
            _i6.Future<_i3.StreamedResponse>.value(_FakeStreamedResponse_2(
          this,
          Invocation.method(
            #send,
            [request],
          ),
        )),
      ) as _i6.Future<_i3.StreamedResponse>);

  @override
  void close() => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MusicServerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMusicServerService extends _i1.Mock
    implements _i10.MusicServerService {
  MockMusicServerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.MusicSearchResult> searchSongs(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchSongs,
          [query],
        ),
        returnValue:
            _i6.Future<_i4.MusicSearchResult>.value(_FakeMusicSearchResult_3(
          this,
          Invocation.method(
            #searchSongs,
            [query],
          ),
        )),
      ) as _i6.Future<_i4.MusicSearchResult>);

  @override
  _i6.Future<List<_i4.Song>> getTrending({
    int? limit = 20,
    List<String>? genres = const [],
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTrending,
          [],
          {
            #limit: limit,
            #genres: genres,
          },
        ),
        returnValue: _i6.Future<List<_i4.Song>>.value(<_i4.Song>[]),
      ) as _i6.Future<List<_i4.Song>>);

  @override
  _i6.Future<List<String>> getSearchSuggestions() => (super.noSuchMethod(
        Invocation.method(
          #getSearchSuggestions,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<String> getStreamUrl(String? videoId) => (super.noSuchMethod(
        Invocation.method(
          #getStreamUrl,
          [videoId],
        ),
        returnValue: _i6.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #getStreamUrl,
            [videoId],
          ),
        )),
      ) as _i6.Future<String>);

  @override
  _i6.Future<void> pushStreamUrl(
    String? id,
    String? streamUrl, {
    bool? isMix = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #pushStreamUrl,
          [
            id,
            streamUrl,
          ],
          {#isMix: isMix},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<List<_i4.Song>> generatePlaylist(
    String? id, {
    int? limit = 30,
    String? search,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #generatePlaylist,
          [id],
          {
            #limit: limit,
            #search: search,
          },
        ),
        returnValue: _i6.Future<List<_i4.Song>>.value(<_i4.Song>[]),
      ) as _i6.Future<List<_i4.Song>>);

  @override
  _i6.Future<Map<String, dynamic>?> getProfile() => (super.noSuchMethod(
        Invocation.method(
          #getProfile,
          [],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Future<List<String>> getLikedSongs() => (super.noSuchMethod(
        Invocation.method(
          #getLikedSongs,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> isSongLiked(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #isSongLiked,
          [songId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> likeSong(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #likeSong,
          [songId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> unlikeSong(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #unlikeSong,
          [songId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<List<String>> getDownloadedSongIds() => (super.noSuchMethod(
        Invocation.method(
          #getDownloadedSongIds,
          [],
        ),
        returnValue: _i6.Future<List<String>>.value(<String>[]),
      ) as _i6.Future<List<String>>);

  @override
  _i6.Future<bool> markDownloaded(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #markDownloaded,
          [songId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> removeDownload(String? songId) => (super.noSuchMethod(
        Invocation.method(
          #removeDownload,
          [songId],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);
}

/// A class which mocks [GeminiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeminiService extends _i1.Mock implements _i11.GeminiService {
  MockGeminiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i11.SongMetadata?> getSongMetadata(String? videoTitle) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSongMetadata,
          [videoTitle],
        ),
        returnValue: _i6.Future<_i11.SongMetadata?>.value(),
      ) as _i6.Future<_i11.SongMetadata?>);
}
